name: create_labels

on:
  push:
    branches:
      - main 

jobs:
  create_labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: list To Do files
        run: |
            ls *.TODO | sed -e 's/.TODO//g' >> $GITHUB_STEP_SUMMARY

      - name: Empty TODO Files
        run: touch home.TODO work.TODO

      - name: Trigger Command
        run: echo "Command Triggered" 

      - name: extract_labels
        run: |
          echo labels="`ls -m *.TODO | sed -e 's/.TODO//g' | sed -e 's/,//g'`" >> $GITHUB_OUTPUT
