name: Discord notification

on:
  workflow_dispatch:

jobs:
  post-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        uses: ./.github/workflows/post_in_discord.yml
        env:
            DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            --title "GitHub Actions"
            --description "First test message from GitHub Actions!"
