name: Discord notification

on:
  workflow_dispatch:

jobs:
  post-to-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Post to Discord
        uses: Ilshidur/github-actions
        with:
          env: DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          args: |
            --title "GitHub Actions"
            --description "First test message from GitHub Actions!"
